version: '3'
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:3000
